export type GalleryRegion = "UK" | "Nigeria";

export type GalleryProminence = "full" | "wide" | "standard" | "portrait";

export type GalleryItem = {
  slug: string;
  region: GalleryRegion;
  src: string;
  alt: string;
  title: string;
  context: string;
  theme: string;
};

export type GalleryBookItem = GalleryItem & {
  chapter: string;
  caption: string;
  prominence: GalleryProminence;
  width: number;
  height: number;
};

export type GalleryBookChapter = {
  title: string;
  intro: string;
};

export type GalleryBookChapterWithItems = GalleryBookChapter & {
  items: GalleryBookItem[];
};

export const galleryItems: GalleryItem[] = [
  {
    slug: "uk-project-me-session",
    region: "UK",
    src: "/images/gallery/uk-project-me-session.webp",
    alt: "Parent carers taking part in a Project ME session",
    title: "Project ME in community",
    context: "Parent carers taking part in a facilitated Project ME session.",
    theme: "Project ME",
  },
  {
    slug: "uk-project-me-group",
    region: "UK",
    src: "/images/gallery/uk-project-me-group.webp",
    alt: "A group presentation during an OAKonsult Project ME event",
    title: "Recognising shared progress",
    context: "A Project ME event marking the group’s progress.",
    theme: "Community",
  },

  {
    slug: "uk-parent-carer-community",
    region: "UK",
    src: "/images/gallery/uk-parent-carer-community.webp",
    alt: "Parent carers connecting during an OAKonsult community activity",
    title: "Connection around the table",
    context: "Parent carers meeting and talking during a community activity.",
    theme: "Parent carers",
  },
  {
    slug: "nigeria-knowledge-radio",
    region: "Nigeria",
    src: "/images/gallery/nigeria-knowledge-radio.webp",
    alt: "OAKonsult disability-awareness engagement at Knowledge Radio",
    title: "Taking inclusion into public conversation",
    context: "An OAKonsult discussion about disability inclusion on Knowledge Radio.",
    theme: "Public awareness",
  },
  {
    slug: "nigeria-press-conference",
    region: "Nigeria",
    src: "/images/gallery/nigeria-press-conference.webp",
    alt: "OAKonsult representatives at a public press conference",
    title: "Building awareness together",
    context: "OAKonsult representatives and partners at a public press event.",
    theme: "Advocacy",
  },
  {
    slug: "nigeria-oolo-palace",
    region: "Nigeria",
    src: "/images/gallery/nigeria-oolo-palace.webp",
    alt: "OAKonsult representatives during a community engagement visit to Oolo Palace",
    title: "Community-rooted relationships",
    context: "OAKonsult meeting local leaders during a community visit.",
    theme: "Community engagement",
  },
  {
    slug: "nigeria-community-session",
    region: "Nigeria",
    src: "/images/impact/nigeria-community-session.jpeg",
    alt: "Adults taking part in a facilitated OAKonsult community session in Nigeria",
    title: "Learning through shared conversation",
    context: "Adults taking part in a facilitated OAKonsult community session in Nigeria.",
    theme: "Community learning",
  },
  {
    slug: "nigeria-community-outreach",
    region: "Nigeria",
    src: "/images/current-site-community-partnership.webp",
    alt: "Five adults together at an indoor community event with information displays behind them",
    title: "Here to help in community spaces",
    context: "OAKonsult representatives at an indoor community event.",
    theme: "Outreach",
  },
  {
    slug: "nigeria-tv-advocacy",
    region: "Nigeria",
    src: "/images/current-site-tv-advocacy.webp",
    alt: "Two adults in conversation during a television studio interview",
    title: "Inclusion in public conversation",
    context: "A television interview about disability inclusion and family support.",
    theme: "Public awareness",
  },
];

export const galleryBookChapters: Record<GalleryRegion, GalleryBookChapter[]> = {
  UK: [
    {
      title: "Learning together",
      intro: "Project ME sessions in Bromley.",
    },
    {
      title: "Wellbeing in motion",
      intro: "Community Zumba for parent carers.",
    },
    {
      title: "Recognition and partnership",
      intro: "The Project ME celebration and certificate presentations.",
    },
  ],
  Nigeria: [
    {
      title: "Community outreach",
      intro: "Visits with schools, local leaders and community partners.",
    },
    {
      title: "Public awareness",
      intro: "Disability inclusion in radio, television and press conversations.",
    },
    {
      title: "Building for the future",
      intro: "The developing OAK Centre Prime site.",
    },
    {
      title: "Medical outreach",
      intro: "Volunteer-led medical outreach in Oolo Town, April 2026.",
    },
  ],
};

export const galleryBookItems: GalleryBookItem[] = [
  {
    slug: "uk-workshop-conversation",
    region: "UK",
    chapter: "Learning together",
    src: "/images/gallery-book/uk/project-me-conversation.webp",
    alt: "Two Project ME participants in conversation at a shared table",
    title: "Conversation around the table",
    caption: "Conversation at a Project ME gathering in Bromley.",
    context: "Conversation and connection during a Project ME gathering in Bromley.",
    theme: "Learning together",
    prominence: "wide",
    width: 2200,
    height: 1466,
  },
  {
    slug: "uk-partner-conversation",
    region: "UK",
    chapter: "Learning together",
    src: "/images/gallery-book/uk/project-me-partner-conversation.webp",
    alt: "Four guests talking together at an OAKonsult event",
    title: "Guests and partners together",
    caption: "Guests at the Project ME celebration.",
    context: "Guests and partners talking together at the Project ME celebration.",
    theme: "Learning together",
    prominence: "standard",
    width: 1800,
    height: 1200,
  },
  {
    slug: "uk-project-me-roundtable",
    region: "UK",
    chapter: "Learning together",
    src: "/images/gallery-book/uk/project-me-roundtable.webp",
    alt: "Project ME participants seated around a table during a facilitated session",
    title: "A session in progress",
    caption: "Parent carers taking part in a Project ME session.",
    context: "A Project ME session in progress, with parent carers learning and contributing together.",
    theme: "Learning together",
    prominence: "portrait",
    width: 1800,
    height: 1800,
  },
  {
    slug: "uk-project-me-shared-table",
    region: "UK",
    chapter: "Learning together",
    src: "/images/gallery-book/uk/project-me-shared-table.webp",
    alt: "Project ME participants sharing a meal and discussion around a meeting table",
    title: "Learning around a shared table",
    caption: "Programme materials, refreshments and conversation at a Project ME session.",
    context: "A Project ME session with programme materials, refreshments and conversation around the table.",
    theme: "Learning together",
    prominence: "portrait",
    width: 1200,
    height: 1600,
  },
  {
    slug: "uk-project-me-participants",
    region: "UK",
    chapter: "Learning together",
    src: "/images/gallery-book/uk/project-me-participants.webp",
    alt: "Project ME participants gathered for a group photograph",
    title: "Time spent learning together",
    caption: "Project ME participants together after a session.",
    context: "Project ME participants marking time spent learning alongside one another.",
    theme: "Learning together",
    prominence: "standard",
    width: 1600,
    height: 1200,
  },
  {
    slug: "uk-listening-together",
    region: "UK",
    chapter: "Learning together",
    src: "/images/gallery-book/uk/project-me-listening.webp",
    alt: "Project ME guests listening from a table during the event",
    title: "Listening and reflecting",
    caption: "Guests listening during a Project ME gathering.",
    context: "Guests listening and reflecting during the Project ME gathering.",
    theme: "Learning together",
    prominence: "standard",
    width: 1800,
    height: 1200,
  },
  {
    slug: "uk-participant-panel",
    region: "UK",
    chapter: "Learning together",
    src: "/images/gallery-book/uk/project-me-participant-panel.webp",
    alt: "Three Project ME guests seated together during the programme event",
    title: "Taking part in the programme",
    caption: "Parent carers and guests at the programme event.",
    context: "Parent carers and guests taking part in the programme event.",
    theme: "Learning together",
    prominence: "standard",
    width: 1800,
    height: 1200,
  },
  {
    slug: "uk-event-audience",
    region: "UK",
    chapter: "Learning together",
    src: "/images/gallery-book/uk/project-me-event-audience.webp",
    alt: "Guests listening from a table at the Project ME celebration",
    title: "A room gathered in Bromley",
    caption: "Participants, supporters and guests gathered in Bromley.",
    context: "A room of supporters, participants and guests gathered in Bromley.",
    theme: "Learning together",
    prominence: "standard",
    width: 1800,
    height: 1200,
  },
  {
    slug: "uk-event-table",
    region: "UK",
    chapter: "Learning together",
    src: "/images/gallery-book/uk/project-me-event-table.webp",
    alt: "Guests in conversation around tables at an OAKonsult event",
    title: "Celebration around the tables",
    caption: "Conversation around the tables at the Project ME celebration.",
    context: "Conversation continued around the tables throughout the celebration.",
    theme: "Learning together",
    prominence: "wide",
    width: 2200,
    height: 1466,
  },
  {
    slug: "uk-zumba-in-motion",
    region: "UK",
    chapter: "Wellbeing in motion",
    src: "/images/gallery-book/uk/parent-carers-zumba-in-motion.webp",
    alt: "Parent carers moving together during an OAKonsult Zumba class",
    title: "Moving together",
    caption: "Parent carers at a community Zumba session.",
    context: "Parent carers moving together in a welcoming community Zumba session.",
    theme: "Wellbeing in motion",
    prominence: "wide",
    width: 2200,
    height: 1466,
  },
  {
    slug: "uk-zumba-community",
    region: "UK",
    chapter: "Wellbeing in motion",
    src: "/images/gallery-book/uk/parent-carers-zumba-community.webp",
    alt: "Six women smiling together after an OAKonsult Zumba class",
    title: "The people behind the movement",
    caption: "The Zumba group after a community session.",
    context: "The people behind the movement: a Zumba group sharing energy and encouragement.",
    theme: "Wellbeing in motion",
    prominence: "standard",
    width: 1800,
    height: 1200,
  },
  {
    slug: "uk-welcome-address",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/project-me-welcome-address.webp",
    alt: "An OAKonsult representative speaking at the Project ME celebration",
    title: "Welcoming our guests",
    caption: "An OAKonsult representative welcomes Project ME guests.",
    context: "Welcoming guests and reflecting on the Project ME journey.",
    theme: "Recognition and partnership",
    prominence: "portrait",
    width: 1800,
    height: 1200,
  },
  {
    slug: "uk-civic-address",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/project-me-civic-address.webp",
    alt: "A civic guest speaking at a lectern during the Project ME celebration",
    title: "A civic welcome in Bromley",
    caption: "A civic guest addresses the Project ME celebration in Bromley.",
    context: "A civic guest addresses the Project ME celebration in Bromley.",
    theme: "Recognition and partnership",
    prominence: "portrait",
    width: 1800,
    height: 1200,
  },
  {
    slug: "uk-certificate-one",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/project-me-certificate-1.webp",
    alt: "A Project ME participant receiving a certificate on stage",
    title: "Recognising commitment",
    caption: "A participant receives a Project ME certificate.",
    context: "Recognising a participant's commitment at the Project ME celebration.",
    theme: "Recognition and partnership",
    prominence: "portrait",
    width: 1200,
    height: 1800,
  },
  {
    slug: "uk-certificate-two",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/project-me-certificate-2.webp",
    alt: "A Project ME participant holding her certificate with event hosts",
    title: "Project ME certificate",
    caption: "A participant with her Project ME certificate.",
    context: "A participant marks the completion of her Project ME journey.",
    theme: "Recognition and partnership",
    prominence: "portrait",
    width: 1288,
    height: 1800,
  },
  {
    slug: "uk-certificate-three",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/project-me-certificate-3.webp",
    alt: "A Project ME participant holding a certificate on stage",
    title: "Celebrating contribution",
    caption: "A participant receives recognition at the Project ME celebration.",
    context: "Celebrating the time, care and contribution invested in Project ME.",
    theme: "Recognition and partnership",
    prominence: "portrait",
    width: 1200,
    height: 1800,
  },
  {
    slug: "uk-community-recognition",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/community-recognition.webp",
    alt: "Three women smiling during an OAKonsult recognition presentation",
    title: "Community contribution recognised",
    caption: "A community recognition presentation at the Project ME celebration.",
    context: "Community contribution recognised during the Project ME celebration.",
    theme: "Recognition and partnership",
    prominence: "standard",
    width: 1200,
    height: 1800,
  },
  {
    slug: "uk-graduation-group",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/project-me-graduation-group.webp",
    alt: "Project ME graduates, guests and OAKonsult representatives gathered on stage",
    title: "Project ME celebration",
    caption: "Project ME participants, supporters and guests together on stage.",
    context: "Project ME participants, supporters and guests gathered to celebrate a shared milestone.",
    theme: "Recognition and partnership",
    prominence: "full",
    width: 2200,
    height: 1466,
  },
  {
    slug: "uk-community-group",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/project-me-community-group.webp",
    alt: "Project ME participants and supporters gathered for a group photograph",
    title: "Participants and supporters",
    caption: "Participants and supporters at the Project ME celebration.",
    context: "Participants and supporters together at the Project ME celebration.",
    theme: "Recognition and partnership",
    prominence: "wide",
    width: 2200,
    height: 1466,
  },
  {
    slug: "uk-partner-group",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/project-me-partner-group.webp",
    alt: "OAKonsult representatives and invited guests at the Project ME celebration",
    title: "Representatives and guests",
    caption: "OAKonsult representatives and invited guests at the Project ME celebration.",
    context: "OAKonsult representatives and invited guests marking the programme celebration.",
    theme: "Recognition and partnership",
    prominence: "standard",
    width: 1800,
    height: 1200,
  },
  {
    slug: "uk-community-partners",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/community-partners.webp",
    alt: "Three OAKonsult community partners smiling together",
    title: "Partnerships that take root",
    caption: "Three OAKonsult community partners.",
    context: "People and partnerships that help community work take root.",
    theme: "Recognition and partnership",
    prominence: "standard",
    width: 1222,
    height: 1800,
  },
  {
    slug: "uk-event-team",
    region: "UK",
    chapter: "Recognition and partnership",
    src: "/images/gallery-book/uk/project-me-event-team.webp",
    alt: "Three OAKonsult representatives at the Project ME celebration",
    title: "The team at the close",
    caption: "OAKonsult representatives at the close of the celebration.",
    context: "OAKonsult representatives together at the close of the celebration.",
    theme: "Recognition and partnership",
    prominence: "standard",
    width: 1200,
    height: 1800,
  },
  {
    slug: "ng-volunteer-meeting",
    region: "Nigeria",
    chapter: "Community outreach",
    src: "/images/gallery-book/nigeria/volunteer-community-meeting.webp",
    alt: "OAKonsult Nigeria volunteers gathered with community members",
    title: "Volunteers in community",
    caption: "Volunteers and community members during an OAKonsult outreach visit.",
    context: "Volunteers and community members gathered during an OAKonsult outreach visit.",
    theme: "Community outreach",
    prominence: "wide",
    width: 2020,
    height: 1472,
  },
  {
    slug: "ng-ogba-school",
    region: "Nigeria",
    chapter: "Community outreach",
    src: "/images/gallery-book/nigeria/ogba-primary-school-visit.webp",
    alt: "OAKonsult representatives with staff during a school visit in Lagos",
    title: "A school visit in Lagos",
    caption: "OAKonsult representatives with staff at Ogba Primary School, Lagos.",
    context: "OAKonsult representatives with staff during a visit to Ogba Primary School, Lagos.",
    theme: "Community outreach",
    prominence: "standard",
    width: 1800,
    height: 1073,
  },
  {
    slug: "ng-kwara-school",
    region: "Nigeria",
    chapter: "Community outreach",
    src: "/images/gallery-book/nigeria/kwara-special-needs-school-visit.webp",
    alt: "OAKonsult representatives with staff during a school visit in Ilorin",
    title: "A school visit in Ilorin",
    caption: "Staff and OAKonsult representatives at Kwara State Special Needs School, Ilorin.",
    context: "Meeting staff during a visit to Kwara State Special Needs School in Ilorin.",
    theme: "Community outreach",
    prominence: "standard",
    width: 1800,
    height: 1067,
  },
  {
    slug: "ng-community-foundation",
    region: "Nigeria",
    chapter: "Community outreach",
    src: "/images/gallery-book/nigeria/agbedare-community-visit.webp",
    alt: "OAKonsult volunteers and community representatives standing together",
    title: "Standing with community representatives",
    caption: "OAKonsult volunteers with community representatives during an outreach visit.",
    context: "OAKonsult volunteers with community representatives during an outreach visit.",
    theme: "Community outreach",
    prominence: "wide",
    width: 1999,
    height: 1365,
  },
  {
    slug: "ng-umca-visit",
    region: "Nigeria",
    chapter: "Community outreach",
    src: "/images/gallery-book/nigeria/umca-institutional-visit.webp",
    alt: "Three representatives during an institutional visit in Ilorin",
    title: "An institutional visit in Ilorin",
    caption: "Representatives visiting UMCA Theological College in Ilorin.",
    context: "Representatives during a visit to UMCA Theological College in Ilorin.",
    theme: "Community outreach",
    prominence: "standard",
    width: 1391,
    height: 909,
  },
  {
    slug: "ng-subeb-meeting",
    region: "Nigeria",
    chapter: "Community outreach",
    src: "/images/gallery-book/nigeria/subeb-partnership-meeting.webp",
    alt: "OAKonsult representatives meeting education-board staff",
    title: "A partnership conversation",
    caption: "OAKonsult meeting State Universal Basic Education Board representatives.",
    context: "A partnership conversation with State Universal Basic Education Board representatives.",
    theme: "Community outreach",
    prominence: "standard",
    width: 1417,
    height: 964,
  },
  {
    slug: "ng-palace-visit",
    region: "Nigeria",
    chapter: "Community outreach",
    src: "/images/gallery-book/nigeria/oolo-palace-community-visit.webp",
    alt: "OAKonsult and community representatives gathered during a palace visit",
    title: "A visit to Oolo Palace",
    caption: "OAKonsult and community representatives at Oolo Palace.",
    context: "OAKonsult and community representatives during a visit to Oolo Palace.",
    theme: "Community outreach",
    prominence: "full",
    width: 2200,
    height: 1650,
  },
  {
    slug: "ng-team-community-event",
    region: "Nigeria",
    chapter: "Community outreach",
    src: "/images/gallery-book/nigeria/oakonsult-team-community-event.webp",
    alt: "OAKonsult Nigeria team gathered at a community event",
    title: "The Nigeria team in community",
    caption: "The OAKonsult Nigeria team at a community event.",
    context: "The OAKonsult Nigeria team gathered during a community event.",
    theme: "Community outreach",
    prominence: "wide",
    width: 720,
    height: 480,
  },
  {
    slug: "ng-team-portrait",
    region: "Nigeria",
    chapter: "Community outreach",
    src: "/images/gallery-book/nigeria/oakonsult-team-portrait.webp",
    alt: "Four OAKonsult Nigeria team members at an event",
    title: "Working together in Nigeria",
    caption: "Four OAKonsult Nigeria team members at an event.",
    context: "OAKonsult team members working together in Nigeria.",
    theme: "Community outreach",
    prominence: "standard",
    width: 646,
    height: 480,
  },
  {
    slug: "ng-knowledge-radio",
    region: "Nigeria",
    chapter: "Public awareness",
    src: "/images/gallery-book/nigeria/knowledge-radio-conversation.webp",
    alt: "OAKonsult representative with a Knowledge Radio host",
    title: "On air at Knowledge Radio",
    caption: "An OAKonsult public-awareness conversation at Knowledge Radio.",
    context: "A public-awareness conversation at Knowledge Radio.",
    theme: "Public awareness",
    prominence: "standard",
    width: 1800,
    height: 1350,
  },
  {
    slug: "ng-naija-fm",
    region: "Nigeria",
    chapter: "Public awareness",
    src: "/images/gallery-book/nigeria/naija-fm-interview.webp",
    alt: "OAKonsult representative seated in a Naija FM studio",
    title: "Talking with Naija FM listeners",
    caption: "An OAKonsult interview at Naija FM.",
    context: "Taking the disability-inclusion conversation to listeners at Naija FM.",
    theme: "Public awareness",
    prominence: "portrait",
    width: 1350,
    height: 1800,
  },
  {
    slug: "ng-press-conference-team",
    region: "Nigeria",
    chapter: "Public awareness",
    src: "/images/gallery-book/nigeria/press-conference-team.webp",
    alt: "OAKonsult representatives holding information materials at a press conference",
    title: "Sharing information with the press",
    caption: "OAKonsult representatives at a press conference.",
    context: "OAKonsult representatives sharing information during a press conference.",
    theme: "Public awareness",
    prominence: "wide",
    width: 2200,
    height: 1650,
  },
  {
    slug: "ng-press-conference-room",
    region: "Nigeria",
    chapter: "Public awareness",
    src: "/images/gallery-book/nigeria/press-conference-room.webp",
    alt: "Speakers and guests gathered in a press-conference room",
    title: "Space for public dialogue",
    caption: "Speakers and guests at an OAKonsult press briefing.",
    context: "A press briefing creates space for wider public understanding and dialogue.",
    theme: "Public awareness",
    prominence: "wide",
    width: 2200,
    height: 1650,
  },
  {
    slug: "ng-silverbird-tv",
    region: "Nigeria",
    chapter: "Public awareness",
    src: "/images/gallery-book/nigeria/silverbird-tv-conversation.webp",
    alt: "OAKonsult representatives taking part in a Silverbird Television studio discussion",
    title: "A studio conversation",
    caption: "OAKonsult representatives discussing disability inclusion on Silverbird Television.",
    context: "A studio conversation with Silverbird Television about disability inclusion and community support.",
    theme: "Public awareness",
    prominence: "wide",
    width: 2200,
    height: 1650,
  },
  {
    slug: "ng-tvc",
    region: "Nigeria",
    chapter: "Public awareness",
    src: "/images/gallery-book/nigeria/tvc-studio-conversation.webp",
    alt: "A television studio interview in progress at TVC",
    title: "Community work on television",
    caption: "An OAKonsult interview at TVC.",
    context: "A TVC studio interview brings OAKonsult's community work to a wider audience.",
    theme: "Public awareness",
    prominence: "portrait",
    width: 1350,
    height: 1800,
  },
  {
    slug: "ng-oak-centre-site",
    region: "Nigeria",
    chapter: "Building for the future",
    src: "/images/gallery-book/nigeria/oak-centre-prime-site.webp",
    alt: "OAKonsult representatives visiting the open site of OAK Centre Prime",
    title: "Walking the OAK Centre Prime site",
    caption: "OAKonsult representatives visiting the OAK Centre Prime site.",
    context: "Walking the OAK Centre Prime site and planning for a long-term base for care, learning and community support.",
    theme: "Building for the future",
    prominence: "full",
    width: 2200,
    height: 1650,
  },
  {
    slug: "ng-medical-supplies",
    region: "Nigeria",
    chapter: "Medical outreach",
    src: "/images/gallery-book/nigeria/medical-outreach-supplies.webp",
    alt: "Volunteers organising supplies at an outdoor medical outreach station",
    title: "Preparing the outreach",
    caption: "Volunteers organising supplies in Oolo Town, April 2026.",
    context: "Volunteers organise supplies at the Oolo Town medical outreach in April 2026.",
    theme: "Medical outreach",
    prominence: "portrait",
    width: 1350,
    height: 1800,
  },
  {
    slug: "ng-medical-station",
    region: "Nigeria",
    chapter: "Medical outreach",
    src: "/images/gallery-book/nigeria/medical-outreach-station.webp",
    alt: "A covered medical-outreach station with supplies arranged on a table",
    title: "A station ready to help",
    caption: "A medical-outreach station prepared in Oolo Town.",
    context: "A medical-outreach station prepared to support children and young people in Oolo Town.",
    theme: "Medical outreach",
    prominence: "portrait",
    width: 1350,
    height: 1800,
  },
  {
    slug: "ng-medical-local-leaders",
    region: "Nigeria",
    chapter: "Medical outreach",
    src: "/images/gallery-book/nigeria/medical-outreach-community-leaders.webp",
    alt: "OAKonsult representatives and community leaders standing at the outreach site",
    title: "Leaders at the outreach site",
    caption: "OAKonsult representatives and community leaders at the outreach site.",
    context: "OAKonsult representatives and community leaders together at the outreach site.",
    theme: "Medical outreach",
    prominence: "wide",
    width: 2200,
    height: 1650,
  },
  {
    slug: "ng-medical-volunteers",
    region: "Nigeria",
    chapter: "Medical outreach",
    src: "/images/gallery-book/nigeria/medical-outreach-volunteers.webp",
    alt: "Medical-outreach volunteers gathered in front of the OAK Centre Prime site board",
    title: "Volunteers at OAK Centre Prime",
    caption: "Volunteers at OAK Centre Prime during the April 2026 outreach.",
    context: "Volunteers gathered during the April 2026 medical outreach at OAK Centre Prime.",
    theme: "Medical outreach",
    prominence: "standard",
    width: 1800,
    height: 1350,
  },
  {
    slug: "ng-medical-team",
    region: "Nigeria",
    chapter: "Medical outreach",
    src: "/images/gallery-book/nigeria/medical-outreach-team.webp",
    alt: "The wider medical-outreach team gathered at OAK Centre Prime",
    title: "April 2026 outreach team",
    caption: "The outreach team at OAK Centre Prime, April 2026.",
    context: "The wider outreach team gathered at the close of a day of coordinated community care.",
    theme: "Medical outreach",
    prominence: "full",
    width: 2200,
    height: 1650,
  },
];

export const galleryBookFor = (region: GalleryRegion): GalleryBookChapterWithItems[] =>
  galleryBookChapters[region].map((chapter) => ({
    ...chapter,
    items: galleryBookItems.filter((item) => item.region === region && item.chapter === chapter.title),
  }));

const homepageBookSlugs = [
  "uk-project-me-roundtable",
  "uk-zumba-in-motion",
  "uk-graduation-group",
  "ng-palace-visit",
  "ng-silverbird-tv",
  "ng-medical-team",
];

export const homepageGallery: GalleryItem[] = homepageBookSlugs.map((slug) => {
  const item = galleryBookItems.find((entry) => entry.slug === slug);
  if (!item) throw new Error(`Missing gallery book item for homepage: ${slug}`);
  return item;
});
