export type LegacyRoute = { source: string; destination: string; note: string };

const preserved = (source: string, note: string): LegacyRoute => ({ source, destination: source, note });
const moved = (source: string, destination: string, note: string): LegacyRoute => ({ source, destination, note });

export const legacyRouteContract: LegacyRoute[] = [
  preserved("/", "Canonical homepage"),
  moved("/about-us", "/about", "Who we are, story, history and inclusion"),
  preserved("/vision-mission", "Dedicated vision, mission, creed and values"),
  preserved("/history", "Dedicated verified timeline"),
  preserved("/our-team", "Current public team information"),
  moved("/partners-supporters", "/funders-partners", "Funders and partners"),
  moved("/annual-reports-impact", "/impact", "Governance and impact"),
  moved("/programs-services", "/what-we-do", "Programme directory"),
  moved("/uk-programs", "/uk", "UK programme hub"),
  moved("/nigeria-programs", "/nigeria", "Nigeria programme hub"),
  preserved("/get-involved", "Participation directory"),
  preserved("/volunteer-opportunities", "Volunteer information and form"),
  moved("/fundraising", "/donate", "Fundraising and giving"),
  preserved("/partnerships", "Partnership and consent-led referral form"),
  moved("/learning-platform", "/what-we-do", "Learning route retained in programme directory"),
  preserved("/events", "Current event routes"),
  moved("/blog-news-stories", "/stories", "News and story index"),
  preserved("/media-gallery", "Regional media gallery"),
  moved("/contact-us", "/contact", "Regional contact routes"),
  moved("/oak-centre-prime", "/programmes/oak-centre-prime", "OAK Centre Prime"),
  moved("/oak-centre", "/programmes/oak-centre-prime", "Architectural and ground-breaking vision"),
  preserved("/projectme", "Project ME interest form"),
  moved("/support-for-parent-carers", "/programmes/parent-carer-support", "Parent-carer support"),
  moved("/support-for-churches", "/programmes/support-for-churches", "Church inclusion support"),
  moved("/job-openings", "/get-involved", "Jobs and opportunities"),
  moved("/uk-media-gallery", "/media-gallery/uk", "UK gallery"),
  moved("/nigeria-media-gallery", "/media-gallery/nigeria", "Nigeria gallery"),
  moved("/nigeria-about-us", "/about", "Shared identity with country-specific Nigeria hub"),
  moved("/nigeria-volunteer-opportunities", "/volunteer-opportunities", "Regional choice retained in form"),
  preserved("/zumba-class", "Dedicated registration page"),
  preserved("/zumba-wellbeing", "Dedicated wellbeing check-in"),
  moved("/uk-funders-partners", "/funders-partners", "Country-specific partner section"),
  moved("/nigeria-funders-partners", "/funders-partners", "Country-specific partner section"),
  moved("/nigeria-community-support", "/nigeria", "Nigeria community support"),
  moved("/talking-faith-for-parent-carers", "/stories", "Faith-sensitive parent-carer content"),
  moved("/january-june-2026-impact-highlights", "/impact", "Verified impact reporting"),
  moved("/a-legacy-of-hope-help-us-build-oak-centre-prime-in-memory-of-abigail", "/abigail", "Abigail and OAK Centre legacy"),
  moved("/why-children-with-disabilities-in-nigeria-are-being-left-behind", "/nigeria", "Nigeria disability context"),
  moved("/raising-our-voices-how-oakonsult-is-igniting-national-awareness-on-disability-in-nigeria-leading-up-to-the-groundbreaking-of-oak-centre-prime", "/programmes/oak-centre-prime", "Awareness and ground-breaking"),
  moved("/three-new-trustees-for-oakonsult-disabilities-outreach", "/our-team", "Trustee information"),
  moved("/medical-outreach-children-young-people-disabilities-april-2026", "/nigeria", "7 April 2026 medical outreach"),
  moved("/bromley-send-local-offer", "/uk", "Bromley SEND partnership update"),
  moved("/care-for-parent-carers", "/donate?purpose=parent-carer", "Giving campaign"),
  moved("/donor-dashboard", "/donate", "Giving journey"),
  moved("/donation-confirmation", "/donate", "Giving journey"),
  moved("/donation-failed", "/donate", "Giving journey"),
  moved("/donations/oak-centre-prime", "/donate?purpose=oak-centre", "OAK Centre giving preference"),
  moved("/donations/care-for-parent-carers", "/donate?purpose=parent-carer", "Parent-carer giving preference"),
  moved("/donations/disability-awareness-training-project-me", "/donate?purpose=project-me", "Project ME giving preference"),
  preserved("/jobs/zumba-group-coordinator", "Opportunity and application form"),
  moved("/volunteer-opportunities/fundraising-partnerships-support", "/volunteer-opportunities", "Volunteer role"),
  moved("/volunteer-opportunities/impact-storytelling-evaluation-officer", "/volunteer-opportunities", "Volunteer role"),
  moved("/category/news", "/stories", "News archive"),
  moved("/category/stories", "/stories", "Story archive"),
  moved("/job-category/community-wellbeing", "/get-involved", "Opportunity taxonomy"),
  moved("/job-type/part-time", "/get-involved", "Opportunity taxonomy"),
  moved("/job-location/bromley", "/get-involved", "Opportunity taxonomy"),
  ...["olufunke-adeloye", "ajisola-adeloye", "itunuade-iyun", "hadiza-daura", "esther-kehinde", "funmilola-oshin", "lucky-aigbefoh", "bunmi-soji-adeyemo", "bolanle-ajayi", "dayo-balogun", "omobola-oludele", "boluwatife-kehinde", "rev-samuel-ajayi", "amb-eunice-eraye-unokhua", "prince-deji-irawo", "dr-olugbenga-owoeye"].map((slug) => moved(`/${slug}`, "/our-team", "Public team profile retained in the team directory")),
];

export const legacyRedirects = legacyRouteContract
  .filter((route) => route.source !== route.destination)
  .map(({ source, destination }) => ({ source, destination, permanent: true }));
